### ISSUE TITLE
Reorder in AboCommerce not possible

### ISSUE THREAD

**Issue by HeX87** [wirecard/shopware-ee#107]
I got this Error if I reorder a order payed whith creditcard in abocommerce.

Could not create order due to a HTTP request exception. URL: https://shop.com/de/de/WirecardElasticEnginePayment/recurring/orderId/97 (Code: 404) in custom/plugins/SwagAboCommerce/Services/OrderCronService.php on line 232
Stack trace:

#0 custom/plugins/SwagAboCommerce/Services/OrderCronService.php(183): SwagAboCommerce\Services\OrderCronService->handleCurl('https://shop.yo...', 1)
#1 custom/plugins/SwagAboCommerce/Controllers/Backend/AboCommerce.php(523): SwagAboCommerce\Services\OrderCronService->createOrder(5)
#2 custom/plugins/SwagAboCommerce/Controllers/Backend/AboCommerce.php(256): Shopware_Controllers_Backend_AboCommerce->createOrder(5)
#3 engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Backend_AboCommerce->createOrderAction()
#4 engine/Library/Enlight/Controller/Dispatcher/Default.php(563): Enlight_Controller_Action->dispatch('createOrderActi...')
#5 engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#6 engine/Shopware/Kernel.php(202): Enlight_Controller_Front->dispatch()
#7 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Shopware\Kernel), Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 engine/Shopware/Components/HttpCache/AppCache.php(260): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
#10 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
#11 engine/Shopware/Components/HttpCache/AppCache.php(105): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true)
#12 shopware.php(122): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}

**Comment by vitali-graz** [comment]
Hi @HeX87 
thank you for bringing up this issue. We are currently evaluating and prioritizing this appropriately.
Best regards,
Wirecard Shop Systems Team

**Comment by Peeet93** [comment]
@vitali-graz is there an update to this issue?
The reorder process is important for our shop
