### ISSUE TITLE
UnknownPaymentException: Unknown Payment '' in PaymentFactory

### ISSUE THREAD

**Issue by ireznik** [wirecard/shopware-ee#179]
Hi,

I see quite often these Entries in the core_production Logs on a Shopware 5.6.6 Installation with running PHP 7.4.5:
`WirecardElasticEngine\Exception\UnknownPaymentException: Unknown payment '' in /custom/plugins/WirecardElasticEngine/Components/Services/PaymentFactory.php:101 Stack trace:
#0 /custom/plugins/WirecardElasticEngine/Controllers/Frontend/WirecardElasticEnginePayment.php(68): WirecardElasticEngine\Components\Services\PaymentFactory->create()
#1 /engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Frontend_WirecardElasticEnginePayment->indexAction()
#2 /engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action->dispatch()
#3 /engine/Library/Enlight/Controller/Front.php(228): Enlight_Controller_Dispatcher_Default->dispatch()
#4 /engine/Shopware/Kernel.php(188): Enlight_Controller_Front->dispatch()
#5 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\Kernel->handle()
#6 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(453): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle()
#7 /engine/Shopware/Components/HttpCache/AppCache.php(261): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward()
#8 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(426): Shopware\Components\HttpCache\AppCache->forward()
#9 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(317): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch()
#10 /engine/Shopware/Components/HttpCache/AppCache.php(188): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup()
#11 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(192): Shopware\Components\HttpCache\AppCache->lookup()
#12 /engine/Shopware/Components/HttpCache/AppCache.php(113): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle()
#13 /var/www/shopware.php(122): Shopware\Components\HttpCache\AppCache->handle()
#14`

I am currently not capable of reproducing this behaviour but wanted to ask if you give me a hint in which direction I shoould look or dig deeper.

**Comment by flavius** [comment]
Hi @ireznik 

Currently, we do not support PHP 7.4. The PHP versions which we support are listed here https://github.com/wirecard/shopware-ee/releases

I would try with PHP 7.2 to see if the problem persists, and if it does, please come back with the exact error, and we'll plan it in.

Either way, please let us know your progress.

Regards,
Wirecard Shopsystems Team

**Comment by ireznik** [comment]
Thanks for the fast feedback. I will provide feedback as fast as possible
